modLoader="javafml" #mandatory
loaderVersion="${forge_range}" #mandatory
license="MIT"
issueTrackerURL="https://github.com/ChiefArug/Skyslands/issues" #optional
[[mods]] #mandatory
modId="skyslands" #mandatory
version="${skyslands_version}" #mandatory
displayName="Skyslands" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/skyslands" #optional
logoFile="pack.png" #optional
credits="" #optional
authors="ChiefArug" #optional
description='''
Sky Island generation for all dimensions!
'''
[[dependencies.skyslands]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.skyslands]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"